### ISSUE TITLE
Implement ReferenceWalker

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#105]
Requires https://github.com/broadinstitute/hellbender/issues/99 as a prerequisite

**Comment by akiezun** [comment]
the requirement is to implement an abstract class `ReferenceWalker` with a method 
```
 public abstract void apply( ReferenceContext referenceContext, VariantContext variant, ReadsContext readsContext, FeatureContext featureContext );
```

that is going to be called for every position in the reference (constrained by -L). Tests are also required.

**Comment by akiezun** [comment]
closing, will reopen if there's a usecase
