### ISSUE TITLE
Add ability to package a monolithic jar (with all dependencies) to the build system

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#106]
Currently our build generates a shell script in build/install/hellbender/bin/hellbender which sets up the Java classpath to point to the various individual jars. We need the ability to package a monolithic jar for distribution, ease of debugging, etc.

**Comment by akiezun** [comment]
@lbergelson is this done by #195 ?

**Comment by akiezun** [comment]
i think it is done by #195. reopen if you disagree
