### ISSUE TITLE
Determine whether and to what degree the GATK engine should provide a reduce facility

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#114]
The current, early-stage ReadWalker interface has only an apply()/map operation. We need to determine whether the GATK engine should accumulate map output and/or provide full reduce functionality, or whether this should be done externally by a separate framework that runs the tools (a la Queue).

**Comment by akiezun** [comment]
i'm going to close this. We'll revisit all designs when we have a few tools working on dataflow
