### ISSUE TITLE
Add per-library option to SplitReads

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/hellbender#140]
Picard has a tool called SplitSamByLibrary. Instead of porting this, we should just add a "split by library" option to SplitReads.

**Comment by akiezun** [comment]
the requirement is that all tests from SplitSamByLibraryTest are implemented in SplitReads. Note that SplitSamByLibrary is not actually in Hellbender.

**Comment by akiezun** [comment]
increasing prio because this functionality is now missing. i'm fine with just porting SplitSamByLibrary for now.

**Comment by cmnbroad** [comment]
Closed via #838.
