### ISSUE TITLE
Force log level to strictest setting for unit tests

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/hellbender#147]
(this is mainly relevant for Picard tools, which often have lots of log.info() calls)

CommandLineProgram's VERBOSITY is set to INFO by default, which is reasonable when you're actually interacting with a tool, but quickly gets spammy when running unit tests. I propose injecting VERBOSITY=ERROR (the strictest setting) into CommandLineProgramTest to avoid this.

This would fix https://github.com/broadinstitute/hellbender/issues/134

**Comment by akiezun** [comment]
unassigning @lbergelson - it's in the current picard sprint.

**Comment by akiezun** [comment]
picard marked as won't fix. back to us

**Comment by cmnbroad** [comment]
The code to automatically inject "--VERBOSITY ERROR" was included in [#171](https://github.com/broadinstitute/hellbender/pull/171/files), but without [#603](https://github.com/broadinstitute/hellbender/pull/603) or equivalent it doesn't affect log4j output. dding in #603 reduces the log output by about another 7000 lines. In addition, we could squeeze out another 5000 lines by automatically injecting "--QUIET false" the same way we inject --VERBOSITY.
