### ISSUE TITLE
Overriding inherited options

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#149]
Tools be able to override the behavior of options they have inherited?

How should this work?  Should you be able to change a required field to an optional one?  Or only the other way around?  

If you override the a field that has an `@Option` annotation does it effectively replace it?

**Comment by akiezun** [comment]
@lbergelson is this solution going in this iteration?

**Comment by akiezun** [comment]
@lbergelson ping

**Comment by lbergelson** [comment]
Oh, sorry, I missed that last comment.  Yeah this should go in.  It's been sitting in local branch, just need to update it.

**Comment by lbergelson** [comment]
This is not resolved in the general case, but it is resolved in the case of the special BAM, reference, and interval options in walkers.  Going to close this.  Reopen when it comes up as an issue again.
