### ISSUE TITLE
ReadsDataSource: enable setting validation stringency

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#181]
it's hardwired to SILENT now

**Comment by akiezun** [comment]
the requirement is that the validation stringency be exposed to the clients of the ReadsDataSource class and tests need to be added. A separate ticket will later be entered for exposing the option at the commandline.

**Comment by cmnbroad** [comment]
I can expose validation stringency, but there is a TODO in this file that says "allow SamReader settings to be customized by client". So my question is similar to the question in issue 419: should  I allow the caller to optionally provide their own SamReaderFactory so they can customize all of the options, or do we really want to just limit it to validation stringency ?

**Comment by akiezun** [comment]
@droazen can you weight in on this?

**Comment by akiezun** [comment]
assigning to me but @cmnbroad is on it

**Comment by cmnbroad** [comment]
PR #585.
