### ISSUE TITLE
See which Picard tools can be easily converted to ReadWalkers

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/hellbender#212]
To help unify things, we should start moving Picard tools to ReadWalkers, where possible. Most of the tools that came from picard.sam should fall under this category.

For tools that can't easily be converted, we should make a note of the traversal pattern so we can consider how to implement it later.

**Comment by akiezun** [comment]
note to assignee: this is a meta issue, when addressing, enter a separate ticket for each tool.

**Comment by akiezun** [comment]
i'm going to close this. we'll pick them one by one
