### ISSUE TITLE
The new annotation engine needs to consider dependencies between annotations.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/hellbender#225]
Some annotations may use as input some other annotations. In this case the former's code should be applied after the all the depends have been applied.

For example QD uses AD and if not present defaults into other sources to determine the read-depth. It can be the case that QD is applied before AD an in the resulting output these two are inconsistent. 

In this case if AD is to be annotated, this should take place before QD is annotated to avoid inconsistencies depending of request list order. 

Here we may consider either to fail if the dependences are not in the list of requested annotations or force the application of those given the list of requested annotations. Non requested annotations could be subsequently stripped from the final output (perhaps this should be explicitly requested by the user).

We could use Java @Annotations to indicate depends between variant annotations (e.g. listing reference to the annotion class object).

**Comment by akiezun** [comment]
not for 4.0
