### ISSUE TITLE
Investigate removing .dict files and only using .fai

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#226]
@lh3 was asking about this in #100

**Comment by akiezun** [comment]
@droazen @lbergelson can you guys make a recommendation here? Are we doing it or not doing it?

**Comment by lbergelson** [comment]
Hmn, I'm not sure I know enough about this one to declare the .dict file dead.  It seems like a good idea to remove it if it's redundant with the .fai though.  Not high priority in any case.

**Comment by droazen** [comment]
Very low priority given that files are not the future

**Comment by akiezun** [comment]
in that case, closing.
