### ISSUE TITLE
All codecs in both tribble and hellbender must implement canDecode()

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#230]
`canDecode()` is now the exclusive means by which we test whether a codec can decode a particular file (can no longer specify the codec manually on the command line as in the old GATK). All codecs should therefore implement this method (currently, only some do). We should:

-Make `canDecode()` abstract in `AbstractFeatureCodec` to force all codec authors to provide an implementation.

-Write implementations of `canDecode()` for all codecs that currently lack it. These can be file-extension-based in most cases. Eg., for `BEDCodec`:

    @Override
    public boolean canDecode(final String path) {
        return path.toLowerCase().endsWith(".bed");
    }

Only some codecs need to examine file contents to determine whether it can decode a file (`VCFCodec` is one such codec, since there are different magic values at file start for different versions of VCF files).

**Comment by akiezun** [comment]
as far as I can tell, all relevant codecs already do implement `canDecode()`. Here's the list of all non-abstract codecs:
in htsjdk:
`BEDCodec` -> implements canDecode
`VCF3Codec` -> implements canDecode 
`VCFCodec`, -> implements canDecode
`BCF2Codec` -> implements canDecode
`ExampleBinaryCodec` (it's an example, I dont care about it) 

(plus deprecated `OldDbSNPCodec`, `GeliTextCodec` - i don't care about those)
And only 1 surving codec in GATK4: `TableCodec` also implements `canDecode`. 

@droazen please list which exact codecs you have in mind here.

**Comment by droazen** [comment]
At the very least we need to remove the default implementation of `canDecode()` in `AbstractFeatureCodec` to force all future codecs to implement it. This implies that we must implement it even for the codecs we don't care about right now.

**Comment by akiezun** [comment]
well, I don't know if I agree. As it is now, it's easier to enforce the property that codecs must UNIQUELY return true for files they support because the default implementation in `AbstractFeatureCodec` returns `false` so it's harder to mess up.

**Comment by droazen** [comment]
The problem is that `canDecode()` used to be just one of several ways by which a codec was selected (eg., users could manually request a codec for a particular file on the command line). Now it is the exclusive means by which codecs are selected in hellbender. This implies that we should take steps to communicate to codec authors that we expect them to implement a sensible `canDecode()` method for each codec by removing the default implementation. For most codecs it will be a one-liner (just check the file extension).

**Comment by droazen** [comment]
This one is not done yet (still requires a pull request into htsjdk).

**Comment by akiezun** [comment]
how are codecs selected in picard or other htsjdk clients?

**Comment by droazen** [comment]
Picard tools generally instantiate the codec they want directly, I believe (no magic). 

`canDecode()` was originally added to the `FeatureCodec` interface by GATK developers (if I remember correctly). Now that the GATK has changed to require `canDecode()`, it needs to become mandatory for codec authors to implement.

**Comment by akiezun** [comment]
done https://github.com/samtools/htsjdk/pull/220

**Comment by akiezun** [comment]
or rather https://github.com/samtools/htsjdk/pull/221
