### ISSUE TITLE
Determine ideal value for FeatureDataSource default query lookahead

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#233]
`DEFAULT_QUERY_LOOKAHEAD_BASES` in `FeatureDataSource` is currently set to 1000. We should empirically determine whether this value results in acceptable performance for typical traversals involving queries over intervals with gradually increasing start/stop positions.

This value controls the number of additional bases by which to expand the END of each query interval that results in a cache miss. Larger values will result in a larger number of cached Features, which will increase the number of cache hits between cache misses, provided query intervals follow the typical pattern of slowly increasing positions. On the other hand, larger values will also increase the cost associated with cache misses, which happen when we jump forward by a large number of bases, switch contigs, or move backwards.

**Comment by akiezun** [comment]
closing this ticket until we determine this is a bottleneck
