### ISSUE TITLE
ReferenceDependentFeatureCodecs are broken and need to be refactored

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#234]
These codecs require a `GenomeLocParser` (and therefore a sequence dictionary), and so are currently broken in hellbender, which does not assume the presence of a sequence dictionary for Feature-containing files. We need to either refactor these codecs to not require a `GenomeLocParser` (and remove the `ReferenceDependentFeatureCodec` interface), or delete them if they are no longer needed.

**Comment by akiezun** [comment]
yes all `ReferenceDependentFeatureCodecs` are dead now, when #363 gets merged.

**Comment by akiezun** [comment]
done in #363
