### ISSUE TITLE
log4j logging level not settable by the user

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#243]
Our current logging level argument (VERBOSITY) is only hooked up to the legacy Picard logger. We need to hook this up to log4j as well.

Related to:
https://github.com/broadinstitute/hellbender/issues/146 (standardize on log4j across GATK + Picard)
https://github.com/broadinstitute/hellbender/issues/216 (fix log4j error that happens on every run)

**Comment by akiezun** [comment]
@lbergelson is this happening this milestone? it does not seem urgent. Why is it marked as a 'bug'?

**Comment by lbergelson** [comment]
It's a bug because we have verbosity setting that doesn't do what it says in many cases.  I don't think it's going to happen for this milestone..

**Comment by droazen** [comment]
`CommandLineProgram.instanceMain()` would be a good place to set the root logging level, after downgrading to log4j 1.x. Don't confuse the Picard logger (the `htsjdk.samtools.util.Log` class) with log4j.

There is current an exposed argument to set the Picard logging level in `CommandLineProgram`:

    @Argument(doc = "Control verbosity of logging.", common=true)
    public Log.LogLevel VERBOSITY = Log.LogLevel.INFO;

You'll need to hook this up to log4j as well, and come up with a unified set of logging levels that work for both log4j and Log.

**Comment by cmnbroad** [comment]
I have a few lines of code that dynamically sets the log4j level for command line tools to match the existing VERBOSITY arg, It seems to work in simple testing so I don't think we need to downgrade to do it. Let me know if you want the code, or if you haven't started you can reassign this to me.

**Comment by edwardkw** [comment]
I've started some work on downgrading, but this definitely sounds like a better solution. I'll reassign to you and if things don't work out you can send it back.

**Comment by cmnbroad** [comment]
Closed #787.
