### ISSUE TITLE
Create a generalized way for tools to request extra context for particular data types

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#245]
There may be a general need to allow tools to request additional context around the current locus/interval. This currently is implemented for `ReferenceContext` via `setWindow()`, but could be expanded to the other *Context classes as well. 

Note, however, that we should not encourage tools to perform arbitrary queries as a general rule, since it would be difficult or impossible to optimize a traversal in which the access pattern is random. If a tool needs to group disparate data items together (eg., mates on different contigs), there should be an initial grouping step to prepare the required data for the main analysis, instead of random queries within the main analysis.

**Comment by akiezun** [comment]
closing until there's a real usecase.
