### ISSUE TITLE
investigate replacing R plotting with javascript plotting

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#248]
Our R dependency is primarily for producing plots.  It could be possible to create plots using javascript instead.  Javascript plots have several potential advantages but also several major downsides.  The biggest and most obvious drawback is that we don't have any code to produce them yet, and they are likely harder to generate and experiment with than R scripts.  

The advantage would be that we could avoid requiring an R installation to run hellbender scripts, we could potentially also include interactive plotting or other neat tricks to make the plots more useful.

I see 2 possible routes to replacing Rscripts with javascript.  The first would be for tools that require graphs to perform some html generation and produce html reports with embedded javascript.  The user could then open these in their browser and view the plots ( much like how our test suite report and jacoco is done).   

A different option would be to use javascript plotting libraries directly within the jvm to generate SVG.  Java 8 has a new javascript engine which is supposed to be reasonably fast and offers access to java objects from within it.  Unfortunately it doesn't offer a full DOM like a browser does, so most existing javascript libraries will fall over.  It seems like it would take a lot of hacking to get something like d3 to run directly on the jvm.  (someone has done something of the kind here: http://jazdw.net/content/server-side-svg-generation-using-d3js)  

Other options would be to use the javafx web panes to display a browser directly, or to plot directly on a canvas.  Either of these options seem like they would be painful and awful.

**Comment by akiezun** [comment]
i'm going to close this. we're not going to implement it.
