### ISSUE TITLE
provide the user with fine-grained control over read filters

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#260]
provide the user with fine-grained control over read filters (should wait until after we see what read filters end up looking like in the dataflow world)

**Comment by akiezun** [comment]
closing. will reopen if this is actually a requirement

**Comment by vdauwera** [comment]
Depends what fine grained control means. User should not have control over default filters that are considered essential by walker authors. User should have control over optional filters that provide eg convenience functions for selecting subsets of data (eg read group based, cigar based, etc).

**Comment by akiezun** [comment]
yes, this ticked was about the former. feel free to enter another ticket for the latter (with a usecase)

**Comment by vdauwera** [comment]
Ok-- off the top of your head, do you already have/plan porting existing read filters?

**Comment by akiezun** [comment]
AFAIK all relevant ones are ported ( #380 being reviewed by @vruano as we speak)
