### ISSUE TITLE
Emit the number of reads filtered out during read traversal, stratified by the filter.

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#262]
Readwalkers should emit the number of reads filtered out stratified by the filter. Note that this requires that filters have names (which they don't currently).

**Comment by akiezun** [comment]
@droazen should this be an engine-level capability? I don't want to duplicate in walkers.

**Comment by droazen** [comment]
Yes, the engine should be responsible for emitting all stats related to traversal/preparation of the data, ideally.

**Comment by lbergelson** [comment]
Relates to #303

**Comment by akiezun** [comment]
Requirements: it's enough to output only the number of reads skipped (ie, not stratify by filter - which would be a bigger task to implement).

**Comment by akiezun** [comment]
@droazen @lbergelson please comment whether you agree with "it's enough to output only the number of reads skipped (ie, not stratify by filter)"

**Comment by lbergelson** [comment]
Better to count the number of reads filtered by any filter than have no
information. Stratification would be good, but it's not the first step.

**Comment by droazen** [comment]
@akiezun Disagree -- this feature is only really useful if you can see why reads are getting filtered out, which implies stratification by filter.

**Comment by vdauwera** [comment]
Stratification by filter should be a requirement! This is hugely useful when diagnosing user issues. I have two cases just this week that I can point you to and it's only Wednesday.

**Comment by akiezun** [comment]
good. a requirement it is.

**Comment by akiezun** [comment]
updated title and added this `Note that this requires that filters have names (which they don't currently).`

**Comment by akiezun** [comment]
assigning to me but @cmnbroad is on it

**Comment by cmnbroad** [comment]
Closed with #613.
