### ISSUE TITLE
Write a BAM file 

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#279]
We'll need to figure out how to do ordering in dataflow.

**Comment by akiezun** [comment]
requirement: code that writes a bam file into a bucket from dataflow. To demonstrate the functionality, the the bam file needs to be bigger than the memory of any single worker and it must have the same content as writing a  bam file from a non-dataflow code.

**Comment by droazen** [comment]
This ticket is partly done, and is superseded by https://github.com/broadinstitute/hellbender/issues/621
