### ISSUE TITLE
Determine how side inputs should be used in hellbender

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#282]
e.g. TSV file for BQSR

**Comment by akiezun** [comment]
@lbergelson can you describe more precisely what the requirements here are? feel free to un-assign after.

**Comment by lbergelson** [comment]
I think we have a good idea of what side inputs are for and when we would need them now.  

My understanding is that side inputs are appropriate to use when you have a fixed object or set of objects which must be provided as a whole to a task or tasks in a pipeline.  If these things can be known at pipeline creation and are inexpensive to generate, it's possible to simply pass the objects as parameters in the pipeline creation.  However, if the object is generated as part of the pipeline, then it must be passed as a side input instead.  

@wbrockman Is my understanding correct?

**Comment by droazen** [comment]
Don't forget the third option (`PCollectionTuple`), which we should explore as well.
