### ISSUE TITLE
Consider using com.google.cloud.dataflow.sdk.transforms.Partition<T> for read/variant filtering

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#303]
Will proposed a novel approach to filtering that could prove useful: instead of running a sequence of filters and discarding items as soon as they fail a filter, use `com.google.cloud.dataflow.sdk.transforms.Partition<T>`  to group items into `PCollections` according to which filters they fail, and then allow a configurable transform to be run on each partition. By default we might just count the number of items failing each filter, but we could have the option of doing things like saving the failing items somewhere for debugging purposes, or outputting for each item the list of ALL filters that it fails.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#2
