### ISSUE TITLE
Help should print required arguments first

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#325]
Currently help output is essentially unordered.  It should have some sorting.  I suggest sorting by required arguments first, then the rest of the arguments.  

Alternatively, they could be sorted in categories by argument collection.  Or we could do both.  Probably  best to sort alphabetically by long name within categories.

**Comment by akiezun** [comment]
assigning to @vdauwera to help specify the requirements here.

**Comment by akiezun** [comment]
assigning to me but @cmnbroad is working on it.

**Comment by cmnbroad** [comment]
Closed with #584
