### ISSUE TITLE
write a custom source for bam files

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#346]
The current bam input code is scary, lets improve it.

**Comment by akiezun** [comment]
@lbergelson please include the pointer to 'the current bam input code' and clarify what needs to be done. assigning to you for now - feel free to unassign when done clarifying

**Comment by jean-philippe-martin** [comment]
I disagree that it's scary, but agree that we want it to be parallel. I take it this ticket means that we decided to go with a custom source implementation? In the email where I shared the workaround, we hadn't yet decided whether to keep the workaround or bite the bullet.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#3
