### ISSUE TITLE
Eliminate compile-time warnings in Picard packages

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#359]
With the migration of the last of the Picard tools came many new compile-time warnings (we went from about 4 warnings up to 100). We should eliminate these.

**Comment by akiezun** [comment]
i think the compiler caps it at 100. there may be more

**Comment by akiezun** [comment]
splitting this into picard vs non-picard and marking accordingly. non-picard is in https://github.com/broadinstitute/hellbender/issues/377

@nh13 please track this ticket - lower prio than tests

**Comment by nh13** [comment]
@droazen I think I know why, but could you articulate why you want no compile time warnings, rather than stating "it is known".

**Comment by mattsooknah** [comment]
For one, it makes it easier to see actual problems in the build because they're not drowned out by tons of warning messages.

**Comment by lbergelson** [comment]
I know that when I download code and build it, I don't find it comforting to see page after page of warnings.

**Comment by nh13** [comment]
That's my thinking too, I would just like to hear why in your own words when we have issues.

**Comment by droazen** [comment]
Comments above by @mattsooknah and @lbergelson reflect my views as well -- allowing lots of warnings to accumulate can hide actual problems. I'll add that `@SuppressWarnings` is a perfectly acceptable approach to dealing with warnings that we've examined and confirmed to be innocuous.

**Comment by droazen** [comment]
@edwardk this one is for you!

**Comment by droazen** [comment]
@edwardkw this one is for you!
