### ISSUE TITLE
picard tests fail sometimes

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#364]
3 tests fail, sometimes. They often pass on a rerun of the build. Here's one example

```
org.broadinstitute.hellbender.tools.picard.illumina.IlluminaBasecallsToSamTest.testMultiplexedWithAlternateBarcodeName FAILED
    java.lang.AssertionError: SAM file output differs from expected output expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:494)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.broadinstitute.hellbender.utils.read.SamAssertionUtils.assertSamsEqual(SamAssertionUtils.java:27)
        at 
```

**Comment by droazen** [comment]
I've seen > 3 of these failures at a time -- I remember seeing 5 or 6 of these fail at once the other day. Possibly an issue with test ordering / statefulness in the test class.

**Comment by akiezun** [comment]
This is urgent. We can either:
* fix this, or 
* disable the tests or 
* remove the code.

**Comment by droazen** [comment]
We should try to fix it, and if we can't after investing an hour or two we should disable the tests until @mattsooknah or somebody else can take a look at them.

**Comment by mattsooknah** [comment]
Sorry I wasn't able to look at this sooner. I'd agree with @droazen - unless the fix is obvious, let's disable those tests for now. I won't have much time to look at it this week, though.

**Comment by lbergelson** [comment]
Did anyone else notice that one of the tests in the `IlluminaBasecallsToSamTest` is in the **broken** test group?

**Comment by lbergelson** [comment]
The comment says it actually should be ok, but it doesn't inspire confidence.

**Comment by lbergelson** [comment]
I don't see any obvious errors.  @droazen Do you have a saved output from one of your failures?  It looks like @vruano has a [failing build](https://travis-ci.org/broadinstitute/hellbender/builds/58471423) that has a similar error in SamComparison failure in BQSR tests, is that actually a bug or is that related to this?

> Gradle test > org.broadinstitute.hellbender.tools.walkers.bqsr.ApplyBQSRIntegrationTest.testPR[2](ApplyBQSR(args=' -qq 6')) FAILED
    java.lang.AssertionError: SAM file output differs from expected output expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:494)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at

**Comment by droazen** [comment]
Unfortunately I never saved the output from my failed builds, but the failures were similar to the one in the original post in this ticket. 

Perhaps we should leave the tests enabled for a bit longer, but modify them to dump the contents of the mismatching output files to the log so we can see what's different about them?

**Comment by lbergelson** [comment]
I opened #375 for that.

**Comment by lbergelson** [comment]
It would be generally useful anyway to get that that information anyway even for non-buggy tests.

**Comment by droazen** [comment]
Check out the most recent failures on Adam's branch (https://travis-ci.org/broadinstitute/hellbender/builds/58486494) -- there is some revealing info in the assertion failures:

org.broadinstitute.hellbender.tools.picard.illumina.parser.IlluminaDataProviderTest.testIlluminaDataProviderBclMethod[0](Bustard Parsing Test(25T8B25T) w/Clocs, 1, 180, [1101, 1201, 2101], [Lorg.broadinstitute.hellbender.tools.picard.illumina.parser.IlluminaDataType;@296e0de9, 25T8B25T, 0, 0, src/test/resources/org/broadinstitute/hellbender/tools/picard/illumina/25T8B25T/Data/Intensities/BaseCalls) FAILED
    java.lang.AssertionError: Bustard Parsing Test(25T8B25T) w/Clocs cluster num 10 expected [2159] but found [1903]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:494)
        at org.testng.Assert.assertEquals(Assert.java:123)
        at org.testng.Assert.assertEquals(Assert.java:370)
        at org.broadinstitute.hellbender.tools.picard.illumina.parser.IlluminaDataProviderTest.comparePositionalData(IlluminaDataProviderTest.java:75)
        at org.broadinstitute.hellbender.tools.picard.illumina.parser.IlluminaDataProviderTest.compareReadData(IlluminaDataProviderTest.java:80)
        at org.broadinstitute.hellbender.tools.picard.illumina.parser.IlluminaDataProviderTest.runTest(IlluminaDataProviderTest.java:37)
        at org.broadinstitute.hellbender.tools.picard.illumina.parser.IlluminaDataProviderTest.testIlluminaDataProviderBclMethod(IlluminaDataProviderTest.java:175)

**Comment by lbergelson** [comment]
Attaching the whole log here: https://gist.github.com/lbergelson/e4babd039228975d3c63

**Comment by droazen** [comment]
Just noticed that the tool in question is using a thread pool...

**Comment by droazen** [comment]
(in `IlluminaBasecallsConverter`)

**Comment by droazen** [comment]
which might explain why we're seeing non-deterministic failures on these tests

**Comment by lbergelson** [comment]
Which would mean there's actually a bug in the tool though, not in the tests.  The results should be deterministic....

**Comment by lbergelson** [comment]
Unless the tests are just not aware of ordering issues in the tool...

**Comment by akiezun** [comment]
we'll disable the tests for BlobFish. @nh13 and the team will fix this in their next sprint.

**Comment by akiezun** [comment]
the fix will not happen this week. for now we'll disable them and picard folks will get it fixed asap in next iteration.

**Comment by droazen** [comment]
Note to whoever takes this issue: need to re-enable tests disabled in https://github.com/broadinstitute/hellbender/pull/379 once they are fixed.

**Comment by nh13** [comment]
@akiezun This is blocked, since we need to know which three unit tests fail and when (reproducible).  If they fail occasionally also we need to know how can we be sure that it is fixed.

**Comment by akiezun** [comment]
the failures are nondeterministic and that in fact is the problem. All tests were disabled in these classes:
```
IlluminaBasecallsToFastqTest
IlluminaBasecallsToSamTest
IlluminaDataProviderTest
```
Have they been failing in the picard repository?

**Comment by akiezun** [comment]
yes they have: https://github.com/broadinstitute/picard/issues/139

**Comment by akiezun** [comment]
@nh13 how can we unblock this?

**Comment by nh13** [comment]
Does anyone on your team have cycles to take a look?

**Comment by mattsooknah** [comment]
Ah yes, I remember this now - they haven't been failing in Picard per se, it's just when we tried compiling under Java 8. The info in that issue should make the fix much easier, if it's indeed the same thing.

**Comment by akiezun** [comment]
perfect. Maybe it's as simple as switching all HashSets to LinkedHashSet
(and same for maps)

**Comment by vdauwera** [comment]
@akiezun Is the work scheduled for your sprint going to fix broadinstitute/picard#139 or should I still plan to throw it in the secon pool? I'm finally catching up on secon work and am prioritizing the inbox so let me know.

**Comment by akiezun** [comment]
@vdauwera My understanding was that the picard folks were on it. If I'm mistaken, decide what you want to do and let me know.

**Comment by lbergelson** [comment]
@akiezun This should be resolved by the removal of these classes yet?

**Comment by akiezun** [comment]
yes: #470
