### ISSUE TITLE
Make warnings into errors

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#368]
The build should fail if it has a warning.

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/hellbender/issues/359

**Comment by akiezun** [comment]
why is this a travis thing? we should not have a difference between travis and local run. Otherwise, you run tests locally, all is good, you push and things break on travis. Not good.

**Comment by lbergelson** [comment]
It shouldn't be a travis thing.  It's a change to the build script that will force travis to reject warnings.  I just phrased the issue the wrong way.

**Comment by lbergelson** [comment]
closed by #576
