### ISSUE TITLE
meta issue: find additional classes with no tests 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#376]
the task is to find all find Picard classes in hellbender with no tests (or very low coverage < 10%) and enter a ticket for each of them. @nh13 please mark this as high priority - lower than the testing bug, higher than writing missing tests (I need to see how much testing we're missing).

**Comment by nh13** [comment]
Any preference for code coverage tool so we can measure similarly, or is the exact number not important just the ballpark?

**Comment by akiezun** [comment]
ballpark is ok - i'm looking for gross offenders here.
we use jacoco (type `gradle jacoco` and it will make html reports)

**Comment by mattsooknah** [comment]
Here's a listing of all ported Picard classes (excluding inner classes) with test coverage of 0%, <10%, and <50%:

https://docs.google.com/a/broadinstitute.com/spreadsheets/d/1ShAuyLmy1zTyFodYMlrCYJgAzF0xj2h4Buzqh75Jjoc/edit?usp=sharing

Anyone feel free to cross things off the list as we add test coverage.

As you can see, there are a lot - do we still want to make individual tickets for all of them?

**Comment by nh13** [comment]
@akiezun can you let us know if this resolves this request?  If so, Matt, first issue is done!

**Comment by akiezun** [comment]
I need a ticket for each of them.

**Comment by nh13** [comment]
@akiezun please be more specific.  There are two issues:
1. Is this request done?
2. Do you have new requests?  If so, lets go through them to make sure we have acceptance criteria.

**Comment by mattsooknah** [comment]
@akiezun for clarification: should we be adding issues for all of the listed classes? Or just a subset (e.g. just CLPs) based on the descriptions you've added in the doc?

**Comment by nh13** [comment]
Could we close this issue as the original request is complete.  We can add new issues for each later.

**Comment by akiezun** [comment]
ok. thanks
