### ISSUE TITLE
Fix coveralls issues caused by transition to public

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#381]
Since the migration from travis-ci.org to travis-ci.com I've been unable to access our coveralls page.  The coverage badge on the repo is broken as well.  Others seem to be able to access the https://coveralls.io/r/broadinstitute/hellbender page, but I get an "Access Denied".  It's still commenting on our posts, but it's not very useful without the actual coverage display.  

I know @droazen can still see the page, @akiezun, can you?  

I filed an issue with coveralls here: https://github.com/lemurheavy/coveralls-public/issues/497 but haven't heard anything back from them.

**Comment by lbergelson** [comment]
Looks like it was an issue on coverall's end.  They fixed it for us.

**Comment by lbergelson** [comment]
Hmn, I may have closed to soon.  It's now visible but doesn't look like it's reporting the right thing.  Maybe it will resolve on further commits...

**Comment by akiezun** [comment]
this looks fixed. the page works. please reopen if there's trouble
