### ISSUE TITLE
put hellbender snapshot jar on maven central

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#384]
we need to be able to create repositories dependent on hellbender and the best way is to make a jar and pot in on maven central. @lbergelson can you look into it? It's pretty high priority because it blocks work on those new repositories

(if there's a solution without maven central, i'm open to it too)

**Comment by lbergelson** [comment]
I've opened a ticket to add hellbender to maven central here:

https://issues.sonatype.org/browse/OSSRH-15070

Once they approve our project as a proper open source project we'll be able to publish it.  I've started the necessary changes to the gradle build based on this tutorial here:  http://jedicoder.blogspot.com/2011/11/automated-gradle-project-deployment-to.html, but can't proceed until we here back from Sonatype.

**Comment by lbergelson** [comment]
As a sidenote, anyone who is going to publish releases needs to sign up for a jira account here: https://issues.sonatype.org.

**Comment by akiezun** [comment]
https://issues.sonatype.org/browse/OSSRH-15070 is now resolved

**Comment by akiezun** [comment]
a requirement is to add a gradle target to deposit a snapshot build on maven central and add text to the readme about how to run it (note: making or depositing release builds is *not* required yet)

**Comment by lbergelson** [comment]
there is now a hellbender snapshot available here: https://oss.sonatype.org/content/groups/public

**Comment by akiezun** [comment]
closing then
