### ISSUE TITLE
implement a way to store and use large files in tests

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#388]
This is very important for integration tests. Not being able to use large files is significantly slowing porting of existing tools to hellbender. Maybe this will work https://git-lfs.github.com/ maybe something else.

**Comment by akiezun** [comment]
a requirement is that we need to store and access the human reference file (~3GB, uncompressed) and a few other files < 1 GB each. The files will have public access so no additional security is required.

**Comment by lbergelson** [comment]
A bit of a side note, but which reference do we want specifically?

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/hellbender/pull/839
