### ISSUE TITLE
port FilterLiftedVariants and add tests

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#39]

**Comment by akiezun** [comment]
the requirement is to port the FilterLiftedVariants tools and the tests from GATK3 (and add more tests because the current ones are very incomplete)

**Comment by eitanbanks** [comment]
FYI Tim Fennell recently implemented a similar tool in Picard.  Only one needs to be ported - I don't care much either way.

**Comment by akiezun** [comment]
not for 4.0
