### ISSUE TITLE
implement BaseRecalibrator on dataflow

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#425]
the requirement for this ticket is to replicate the existing functionality (ie make recalibration tables in the same format as now).

**Comment by akiezun** [comment]
@jean-philippe-martin can you describe the current state?

**Comment by jean-philippe-martin** [comment]
It's done, with tests that work locally and on the cloud. However once the skeleton is in we may want to change it to match.

**Comment by jean-philippe-martin** [comment]
The corresponding pull request is #529. It's merged, so closing this issue.
