### ISSUE TITLE
implement ApplyBQSR on dataflow

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#426]
requirement for this ticket is to replicate the current gatk4 functionality (and make tests pass). We'll work from text-based recalibration tables for now.

**Comment by akiezun** [comment]
@jean-philippe-martin can you describe the current status?

**Comment by jean-philippe-martin** [comment]
Works with local files, and a PR for cloud functionality (complete with passing test) is under review (it's PR #595). The one thing left to do is to adapt to the skeleton once that's merged in.

**Comment by akiezun** [comment]
is this done?

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#4
