### ISSUE TITLE
Clarify spec for valid CIGAR 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#428]
These questions came up in the review of GoodCigarFilter https://github.com/broadinstitute/hellbender/pull/380

The task is clarify the CIGAR validity requirements with the SAM spec and experts and report findings here and then enter issue tickets for every problem found.

* Do we need to filter out operators with 0 length. Currently we do (GoodCigarFilter).
* Do we care if the cigar has consecutive operators of the same kind? Why should GoodCigarFilter fail for two consecutive insertions (xIyI where x and y are numbers) but not for consecutive match (xMyM). as it does now?
* Why should GoodCigarFilter not allow for a Insertion to be followed by a Deletion or vice-versa? It may be a genuine possibility, otherwise we are forcing an artifactual base map.

**Comment by vdauwera** [comment]
For repeated operators (whether xIyI or xMyM), I think GATK3 has/had a function to simplify cigars to "sanitize" that situation. In terms of desired behavior, we don't want to filter out the reads, we want to transform them to be processable without difficulty.

I think xIyD should be considered valid.

**Comment by lbergelson** [comment]
There should probably be a preferred ordering for an insertion followed by a deletion.   Either insertion then deletion or the other way around.

Should cigar normalization be moved from a rejection filter to a corrective ReadTransformer?

**Comment by vdauwera** [comment]
Yes please. I believe gatk3 has at least one read transformer that corrects cigars, if not more. See -fixNDN argument.

**Comment by akiezun** [comment]
Here's what the SAM Spec says:
```
* CIGAR has to be from the regexp: \*|([0-9]+[MIDNSHPX=])+
• H can only be present as the first and/or last operation.
• S may only have H operations between them and the ends of the CIGAR string.
• For mRNA-to-genome alignment, an N operation represents an intron. For other types of
alignments, the interpretation of N is not defined.
• Sum of lengths of the M/I/S/=/X operations shall equal the length of SEQ.
```

And in the 'recommended practice' part:
```
* Adjacent CIGAR operations should be different.
```

And that's it in the spec, the rest is just GATK wisdom and practice, not a question of spec. So it seems to me we may need 2 separate filters: one for reads failing the spec (nothing can save those and we will always toss them), and second one for reads that GATK wisdom says are bad (but someone else's wisdom may say otherwise). 

@eitanbanks and @droazen do you know why the following 'wisdom-based' conditions were introduced:
 1) No reads starting with deletions (with or without preceding clips)
 2) No reads ending in deletions (with or without follow-up clips)
 3) No reads that are fully hard or soft clipped
 4) No reads that have consecutive indels in the cigar (II, DD, ID or DI)
 
and does GATK3 not enforce the "Adjacent CIGAR operations should be different." recommendation ?

**Comment by akiezun** [comment]
i'm closing this. I dont see any action to be done. Reopen if something changes.
