### ISSUE TITLE
Add more read filters

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/hellbender#429]
Use case 1: I want to operate on a subset of my bam by blacklisting or whitelisting reads that have a particular read group property. GATK3 analogs: SingleReadGroupFilter, SampleFilter, ReadNameFilter, ReadGroupBlackListFilter, PlatformUnitFilter, PlatformFilter, LibraryReadFilter. 

Use case 2: I want to operate on a subset of my bam by blacklisting or whitelisting reads that have a particular "physical" property. GATK3 analogs: MaxInsertSizeFilter, ReadLengthFilter, ReadStrandFilter.

Use case 3: I want to operate on a subset of my bam by blacklisting or whitelisting reads that have a particular mapping property. GATK3 analogs: MappingQualityFilter, MappingQualityUnavailableFilter, MappingQualityZeroFilter, UnmappedReadFilter. Feature request: add ability to recognize a cigar pattern (to e.g. select reads with insertions> 10 bases, or reads with soft-clips, etc). 

Use case 4: I want to operate on a subset of my bam by blacklisting or whitelisting read pairs that have particular pairing properties. GATK3 analogs: BadMateFilter, MateSameStrandFilter.

**Comment by akiezun** [comment]
in pull #454 i added all those filters.
What remains to be done is hooking them up to the argument parsing system and the engine and your feature request "add ability to recognize a cigar pattern (to e.g. select reads with insertions> 10 bases, or reads with soft-clips, etc)." 
Once #454 is merged, will close this ticket and open separate one for those two outstanding issues.
Assigning to me to remember.

**Comment by vdauwera** [comment]
Yay, thanks @akiezun

**Comment by akiezun** [comment]
added https://github.com/broadinstitute/hellbender/issues/589
closing this issue as discussed
