### ISSUE TITLE
Implement Circular Binary Segmentation algorithm

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#431]
We need to have a Circular Binary Segmentation algorithm implementation in Java. The algorithm is described here:
Olshen, A. B., Venkatraman, E. S., Lucito, R., and Wigler, M. (2004).
Circular binary segmentation for the analysis of array-based dna copy
number data. Biostatistics, 5:557–72.

and speed improvements described here:
Venkatraman, E. S. and Olshen, A. B. (2007). A faster circular binary
segmentation algorithm for the analysis of array cgh data. Bioinformatics,
23:657–63.

The R implementation is in the DNACopy package:
http://bioconductor.wustl.edu/bioc/vignettes/DNAcopy/inst/doc/DNAcopy.pdf

The requirement is to take data from the R package and implement the algorithm to produce results equivalent to those from R (there may be small differences due to random number generation).

**Comment by akiezun** [comment]
@cwhelan and @LeeTL1220 please chip in regarding requirements.

**Comment by akiezun** [comment]
the speed requirement is to be within 5x of the R code.

**Comment by akiezun** [comment]
it's acceptable to call out to R as the first version of the algorithm. Use `RScriptExecutor`

**Comment by vruano** [comment]
Ported to hellbender-protected: https://github.com/broadinstitute/hellbender-protected/issues/10
