### ISSUE TITLE
get gcloud authorization working on travis

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#444]
Any test that tries to access a bucket seems to stall indefinitely. I think this has to do with gcloud not accepting our credentials file on travis.  I suspect it's trying to open a web browser.  I suspect it may need to be reconfigured with a service account key and an explicit authorization step before the build.

**Comment by akiezun** [comment]
@wbrockman can you advise on this?

**Comment by droazen** [comment]
@lbergelson This one is done, right?
