### ISSUE TITLE
replace custom MannWhitneyU with Apache math

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#446]

**Comment by ldgauthier** [comment]
Having just dug though all the GATK 3 rank sum code, I +1 this as long as we can segregate (or optionally  turn off) the random number generator calls so the annotations don't change hc/m2 downsampling.

**Comment by akiezun** [comment]
the default Apache implementation uses deterministic tie handling (average ranks) but has a randomized option if we want. https://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math3/stat/ranking/TiesStrategy.html

**Comment by akiezun** [comment]
i'll take it - i want this ugly code out of hellbender

**Comment by ldgauthier** [comment]
Sounds good -- +1

**Comment by akiezun** [comment]
reluctantly closing this. The apache version does not implement it properly for low counts.
