### ISSUE TITLE
optional/required argument collections need tests and/or examples

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#451]
came up in review of #449 

the following classes are unused code. they need examples and tests to show how to use them.

OptionalFeatureInputArgumentCollection
RequiredFeatureInputArgumentCollection
RequiredReadInputArgumentCollection
RequiredReferenceInputArgumentCollection
RequiredVariantInputArgumentCollection

**Comment by droazen** [comment]
This ticket is silly -- these are argument collections, not actual code that needs tests. Each of these classes just contains an annotated argument variable. Each class also has comments explaining when a tool would want to use each argument collection. Closing!
