### ISSUE TITLE
Support interval input in dataflow read pre-processing pipeline

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#461]

**Comment by lbergelson** [comment]
Since I don't think we have a standard yet, maybe we could use either `SimpleInterval` or `Locatable` as our standard here.

**Comment by lbergelson** [comment]
Locatable isn't serializable so it's probably not ideal...

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#6
