### ISSUE TITLE
Figure out best way to combine data for "nearby" intervals in dataflow

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#469]
Needed for `RealignerTargetCreator`

**Comment by droazen** [comment]
One option is `Combine.globally()` on a tree

**Comment by lbergelson** [comment]
For improving performance by rapidly joining local sites we could do something like:

PCollection<Event>   -> key event by which 10kb window of the genome it falls into 
keyed events -> Combine.PerKey into interval trees
combined keyed events -> drop keys
Combine.globally the interval trees into a single interval tree

**Comment by akiezun** [comment]
FYI RealignerTargetCreator is not getting ported to hellbender

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#33
