### ISSUE TITLE
Filter reads with no bases mapped to the reference

### ISSUE THREAD

**Issue by vruano** [broadinstitute/hellbender#484]
Currently the ExomeReadCounts tool (an any other ReadWalker) crashes when encounters a read that have a CIGAR devoid of operators that consume reference bases. 

There is another issue open on the matter in order to find a solution for all ReadWalkers: https://github.com/broadinstitute/hellbender/issues/373.

Since we are not to count those reads at all, which would "fix" the reported bug for that tool.

**Comment by akiezun** [comment]
should this filter be added to WELLFORMED filter? That is, should this be filter that *all* readwalkers use?

**Comment by vruano** [comment]
Don't know, the question is how this cigars came to exist. I guess is the product of some kind of re-alignment and it so they still may confer some information about the region they are contained in that is of some value for some analysis.

**Comment by vruano** [comment]
The last merge addressed this issue. Whether this filter should be added to WELLFORMED can be addressed in another issue https://github.com/broadinstitute/hellbender/issues/373.
