### ISSUE TITLE
Default Java version mismatch error message

### ISSUE THREAD

**Issue by jmthibault79** [broadinstitute/hellbender#489]
I have Java 8 installed, but it's not my *default* Java version, so `gradle check` gives me this error message:
```
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> invalid source release: 1.8
```

`JAVA_HOME=$JAVA8_HOME gradle check` succeeded. 

I would prefer an error message like "Hellbender requires JAVA_HOME to point to a valid Java 8 installation" to make it immediately obvious what needs to be done.

**Comment by lbergelson** [comment]
That would be a clearer error message.

**Comment by akiezun** [comment]
closing. `invalid source release: 1.8` is pretty clear

**Comment by jmthibault79** [comment]
Disagree.  For sophisticated Java developers like us, it's clear enough.  But will the average GATK user know that `source release 1.8` refers to **Java 8**, and that they may need to set their Java default version **manually** even after installing Java 8?  Would like to hear from @vdauwera on this.
