### ISSUE TITLE
replace obsolete Date with Java8 date time abstractions

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#496]
Date is obsolete, we need to use java.time
https://docs.oracle.com/javase/tutorial/datetime/index.html

**Comment by cmnbroad** [comment]
Looks like there are only a few direct references, but there are transitive dependencies on Date and Date-derived classes (i.e. Iso8601Date) via htsjdk/SAMTools.

**Comment by akiezun** [comment]
That's fine, don't worry about those.

**Comment by cmnbroad** [comment]
#534
