### ISSUE TITLE
Allow common dataflow options to be specified via a config file

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#508]
Would be nice if common, rarely-changing dataflow options like the project and client secret could be specified in a config file rather than as part of every hellbender command.

**Comment by lbergelson** [comment]
You can kind of do this right now by specifying --arguments_file and pointing to a file with those arguments.

**Comment by droazen** [comment]
Good to know -- forgot that we had `--arguments_file`. 

The advantage of the config file approach would be that you wouldn't have to specify any extra args -- it would just look in the current directory or a known location for a file with your dataflow settings. Things like the pipeline runner would probably still be manually specified, though (perhaps with nice aliases like `--cloud` and `--local`)

**Comment by lbergelson** [comment]
config file is good for convenience, but I find that they cause lots of confusion and errors because people forget their existence

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#13
