### ISSUE TITLE
ReadBAMTransform.getReadsFromBAMFilesSharded() is flawed

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#509]
`ReadBAMTransform.getReadsFromBAMFilesSharded()` (which we rely upon to produce initial `PCollection<Read>`s in our pipelines) relies on flawed conversion from `SAMRecord` to `Read` (`ReadConverter.makeRead()`) that (among other things) does not encode attributes correctly. It also does not support unmapped reads. We should fix these issues.

**Comment by droazen** [comment]
`DataflowUtils.getReadsFromLocalBams()` also relies on `ReadCoverter.makeRead()` and should be fixed as well.

**Comment by lbergelson** [comment]
How should we resolve this? By patching the google repos or by copying / creating our own?  Seems like patching google is probably the right way to go, but we're blocked by lawyers.

**Comment by droazen** [comment]
Replace `ReadCoverter.makeRead()` completely, copy `ReadBAMTransform.getReadsFromBAMFilesSharded()` and associated code to hellbender and add tests for it.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#12
