### ISSUE TITLE
Remove use of GenomicsSecretsFile and instead use SecretsFile

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/hellbender#516]
The GenomicsSecretsFile is no longer needed at all. Fix its use in DataflowCommandLineProgram.

**Comment by jean-philippe-martin** [comment]
I need to do this for the BQSR Travis tests anyways, so I'll go ahead and do it (branch name is jp_CloudTests, though depending on when you read this I may not have pushed it yet).

**Comment by jean-philippe-martin** [comment]
done in PR #535
