### ISSUE TITLE
Is WordCount.java needed?

### ISSUE THREAD

**Issue by pgrosu** [broadinstitute/hellbender#533]
Maybe there is a reason, but I'm not sure for what part of the project the [WordCount.java](https://github.com/broadinstitute/hellbender/blob/master/src/main/java/org/broadinstitute/hellbender/tools/dataflow/WordCount.java) file might be needed:

https://github.com/broadinstitute/hellbender/blob/master/src/main/java/org/broadinstitute/hellbender/tools/dataflow/WordCount.java

Thanks,
Paul

**Comment by lbergelson** [comment]
It's not needed.  It was a demonstration program for `DataflowCommandLineProgram`  It could either be deleted or renamed as `ExampleDataflowCommandLineProgram`  I think I would go with delete.

**Comment by akiezun** [comment]
I would rename it. Having a helloworld program such as this is not a terrible idea.

**Comment by pgrosu** [comment]
You're right, having a demonstration helloworld problem is not a bad idea to get people comfortable with Dataflow.  Thanks for helping me,  I can close the issue for now.

Thanks,
Paul

**Comment by lbergelson** [comment]
Opened #537 so that we do the rename.
