### ISSUE TITLE
Add Spark tests to travis matrix

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#551]
We should run all of our dataflow tests on spark local runner as well as the dataflow direct pipeline runner.  The plan is to run these as "optional" tests so that spark failure doesn't block our builds but we will be aware of any differences between the spark and google implementations.

**Comment by akiezun** [comment]
@tomwhite can you help with this?

**Comment by tomwhite** [comment]
@akiezun yes, I can take a look.
