### ISSUE TITLE
Support reading reference sequences from Spark/Hadoop

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/hellbender#567]
This is needed to support the work being done in https://github.com/broadinstitute/hellbender/tree/dr_read_preprocessing_pipeline_skeleton, for example. 

One way to do this is to broadcast the entire reference sequence to all nodes in the cluster. I've tried another approach which does streaming reads from HDFS here: https://github.com/broadinstitute/hellbender/compare/master...tomwhite:hadoop-references. It uses a modified version of htsjdk's IndexedFastaSequenceFile that reads from HDFS rather than a local file. IndexedFastaSequenceFile is very file-centric and not really designed for extension, so a certain amount of trickery is needed.

Any thoughts about the approaches?

**Comment by lbergelson** [comment]
I think we should have @droazen and @davidaadams chime in on this one.

**Comment by droazen** [comment]
I think it would be good to profile and compare a variety of approaches for dealing with the reference data. In the dr_read_preprocessing_pipeline_skeleton branch we are taking the approach of sharding the reference into fixed-size chunks, and using GA4GH API calls (rather than files) to populate each chunk. We currently have no idea how well this will perform, though we suspect it will be better than copying the entire reference to each worker.

@tomwhite Would it be possible at this point to profile the two options you mentioned ("broadcast the entire reference sequence to all nodes in the cluster" vs. "streaming reads from HDFS") with a real human reference like GRCh37 so that we can make an informed choice between them?

**Comment by pgrosu** [comment]
@droazen Not sure reference via GA4GH is shardable or currently implemeted via [gRPC](http://www.grpc.io/) but let's see - I'm curious on the statistics too.  I assume you are referring to the following:

https://cloud.google.com/genomics/v1beta2/reference/references
https://cloud.google.com/genomics/v1beta2/reference/references/bases
https://cloud.google.com/genomics/v1beta2/reference/referencesets

~p

**Comment by cwhelan** [comment]
Just to chime in with some possibly-not-relevant experience, I had pretty good luck in my past life distributing references (the BWA index, in my case) with Hadoop's distributed cache mechanism (which I guess is similar to broadcasting in Spark?). It would sort of saturate the network, though, when a big job was starting up, and I guess the characteristics of the network you're running on could make a difference.

**Comment by pgrosu** [comment]
@cwhelan All experience is relevant :)  That is a nice approach - do you have a link regarding the possible implementation?

Thanks,
Paul

**Comment by tomwhite** [comment]
The approach I've taken in https://github.com/broadinstitute/hellbender/compare/master...tomwhite:hadoop-references is similar to sharding, in that each worker streams the portion that it needs from HDFS.

@droazen I agree that comparing with a "broadcast everything" approach would be valuable - I'll write some code to do that and create a PR for it.

@cwhelan - it's very similar to the Hadoop distributed cache, the main difference is that Spark uses a BitTorrent-like mechanism for distributing the data, which is more efficient for the network. You still need the memory to store the data in on the nodes, which for a genome is ~3GB. But that shouldn't be too onerous with modern hardware.

**Comment by cwhelan** [comment]
@pgrosu Here's how I did it, although this was using the old mapred Hadoop 1.0 API so would be deprecated now.

This class adds a bunch of BWA index files to the distributed cache:

https://github.com/cwhelan/cloudbreak/blob/master/src/main/java/edu/ohsu/sonmezsysbio/cloudbreak/command/CommandBWAPairedEnds.java

By calling into the addDistributedCacheFile method here:

https://github.com/cwhelan/cloudbreak/blob/master/src/main/java/edu/ohsu/sonmezsysbio/cloudbreak/command/BaseCloudbreakCommand.java

This mapper class can then just reference them as local files on the executing node:

https://github.com/cwhelan/cloudbreak/blob/master/src/main/java/edu/ohsu/sonmezsysbio/cloudbreak/mapper/BWAPairedEndMapper.java

Feel free to poke around that repo if you find it interesting.

**Comment by droazen** [comment]
@pgrosu The GA4GH API supports reference queries by interval (https://cloud.google.com/genomics/v1beta2/reference/references/bases/list), which allows us to do manual sharding of the reference data.

@tomwhite Sounds good! Will be interesting to see the results of the comparison.

**Comment by pgrosu** [comment]
@droazen Yeah, that would work - didn't think of it that way :)  I just ran a quick test using the following command, while changing the `end`:

```
time( java -jar genomics-tools-client-java-v1beta2.jar getreferencebases --id EPDikenvqJioOA --start 1 --end 1000000 )
```

There seems to be a point where it starts to get faster when the regions are longer or if you have many multiple small-region requests:

start | end | time to retrieve region (seconds) | 	total human genome | total time retrieve genome (seconds)
------|------|------|------|------
1 | 1000 | 2.13 | 3234830000 | 6890187.9
1 | 100000 | 2.183 | 3234830000 | 70616.3389
1 | 1000000 | 4.087 | 3234830000 | 13220.75021
1 | 10000000 | 22.328 | 3234830000 | 7222.728424
1 | 1000000000 | 298.418 | 3234830000 | 965.3314989

Looks promising but I'm still curious of the offical times :)

~p

**Comment by tomwhite** [comment]
I added a small test demonstrating how to broadcast the reference sequence here: https://github.com/broadinstitute/hellbender/compare/master...tomwhite:hadoop-references#diff-957e843e027a45b3ac07d9a6c0515534R42

This will need to be run on a cluster to see how it performs, but I'd like to understand better how it will fit into the work in the dr_read_preprocessing_pipeline_skeleton branch. What is the integration point ther do you think @droazen?

**Comment by droazen** [comment]
Seems like we'll need to either create some mechanism for selecting between `ReferenceFileSource` and `RefAPISource` based on the user's arguments, or unify those two classes. Either way, I think we can do this integration work as a separate step after all of these branches are in master.

**Comment by tomwhite** [comment]
I did some more work on the broadcast approach to see how feasible it would be, and found that Spark Dataflow made two unnecessary copies of the data (now fixed: https://github.com/cloudera/spark-dataflow/pull/60), which caused OOM errors when trying to broadcast the 3GB reference data.

With this fixed, I ran a [pipeline called JoinReferencesDataflow](https://github.com/tomwhite/hellbender/blob/hadoop-references/src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/JoinReferencesDataflow.java) on a small cluster that broadcasts the reference as a dataflow view. The code is a modified version of CountReadsDataflow that simply sends the view, and then doesn't use it, so we can see the cost of doing a broadcast (See the rest of the code in this branch: https://github.com/tomwhite/hellbender/tree/hadoop-references.)

JoinReferencesDataflow took 2 min 25s to run, of which 18s were for reading the reference from the local filesystem in the driver. For comparison, CountReadsDataflow took 17s on the same cluster. So broadcasting the reference takes less than 2 minutes. Note that this was just for one task, but Spark has [an efficient protocol for sending broadcast variables](http://www.cs.berkeley.edu/~agearh/cs267.sp10/files/mosharaf-spark-bc-report-spring10.pdf), which scales well with the number of nodes, so the approach looks feasible.

Having said all that, we might still want to use the sharding approach, in order to share more code between the Google and Spark dataflow implementations. One way this could work would be to generalize `RefAPISource` and `RefAPIMetadata` to support reading reference data from a [ReferenceHadoopSource](https://github.com/tomwhite/hellbender/blob/hadoop-references/src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReferenceHadoopSource.java), which is in line with @droazen's last comment.

Am I right in thinking that the read pipeline work is being completed in https://github.com/broadinstitute/hellbender/tree/da_read_pipeline? Is that at a point where I could try with pipeline on Spark, or should I wait until it's merged?

**Comment by davidadamsphd** [comment]
da_read_pipeline is the right spot. If it's OK, I suggest holding off for a little bit. That branch is next in queue to get merged. I plan to have it merged by next Friday. Until then, I'll be doing (hopefully small) cleanup. I don't expect any serious refactors, but it hasn't gone for review, so I can't promise anything. (Read: it probably won't change much, but I can't guarantee it, so using it may waste some of your time)

Right after that goes in, I want to work with you Tom on a refactor that'll work well for everyone. There many also be other places where we're overly tied to Cloud Dataflow right now.

**Comment by tomwhite** [comment]
Thanks for the update @davidadamsphd - sounds good to me.

**Comment by tomwhite** [comment]
Now that the read processing pipeline code is in, I've rebased https://github.com/broadinstitute/hellbender/compare/master...tomwhite:hadoop-references which demonstrates some different approaches on the Hadoop side. The question is, how should we combine the approaches so that references work for Cloud and Hadoop?

**Comment by davidadamsphd** [comment]
Nice! I've started to look at your branch (thought I haven't made all the way through). I think we should have a virtual face-to-face to talk over the options. (Moving off-thread for now).

**Comment by tomwhite** [comment]
Fixed in https://github.com/broadinstitute/hellbender/pull/827
