### ISSUE TITLE
Fix broken test input: NA12878.chr17_69k_70k.dictFix.bam

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/hellbender#568]
This test input is malformed. When I try to read it with the Dataflow code, I get this error:

htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 129, Read name 809R9ABXX101220:5:6:17918:145992, Mate Alignment start should be 0 because reference name = *.

Here's the corresponding read:

809R9ABXX101220:5:6:17918:145992        97      17      69400   37      67M9S   *       71202348        0       ACTCCCCACCTTACCTGACTCCTTCCAGGGTTTGTCGCCTTTCCGGTCCCTGACCCCAGTGGATGGGAGTCTGTCC    ?ABDDEEABEECBDBDAB=DEDCDEEBFADABCEAD?EEEDCFE?ABEEE@FCDEEEBF@F?C<E@##########    MD:Z:67 PG:Z:BWA        RG:Z:809R9.5    AM:i:0  NM:i:0  SM:i:37 MQ:i:0  OQ:Z:DGEGGGGBFGGGGGDF8@@FGFBGGGBGCECCEEDFGGGFGFGGGBDGGF9DBFFGFBF;@>A4@@##########       UQ:i:0

@droazen confirms that Picard's ValidateSAMFile utility reports that this bam has multiple errors.

We should replace it with a clean input, and update the "known good" output accordingly.

**Comment by jean-philippe-martin** [comment]
This falls under the newly-created #569

**Comment by dr** [comment]
I don't think you meant to tag @DR in this :)

**Comment by lbergelson** [comment]
Now that we've tagged you once accidentally you show up as a suggested person so you keep getting tagged.  You seem to be a permanent project member now.  Might as well start contributing code :)

**Comment by dr** [comment]
Whew… I'm rusty but I'll start practicing!

**Comment by jean-philippe-martin** [comment]
correct, @DR, sorry about that :)

**Comment by akiezun** [comment]
@jean-philippe-martin should we close this in favor of #569?

**Comment by jean-philippe-martin** [comment]
@akiezun if you like, sure. In that case just copy the text here and place it in a comment in the other one, perhaps, so we remember to check that particular read?

**Comment by akiezun** [comment]
closing as dup of #569
