### ISSUE TITLE
Fix the four warnings about google files

### ISSUE THREAD

**Issue by edwardkw** [broadinstitute/hellbender#573]
Example:
Warning:java: Cannot find annotation method 'emulated()' in type 'com.google.appengine.repackaged.com.google.common.annotations.GwtCompatible': class file for com.google.appengine.repackaged.com.google.common.annotations.GwtCompatible not found

**Comment by droazen** [comment]
David A points out that we have imports like this in tests:

`import com.google.appengine.repackaged.com.google.common.collect.Lists;`

For `Lists.newArrayList()` (which I think could be trivially replaced with `Arrays.asList()`! Might be related!

**Comment by lbergelson** [comment]
Why didn't we find that when we searched for it?

**Comment by droazen** [comment]
I think because we searched for a slightly different package.

**Comment by lbergelson** [comment]
bah, humbug
