### ISSUE TITLE
Automatic sequence dictionary validation for spark tools

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#669]
All walkers now have comprehensive sequence dictionary validation performed on their inputs (via the `GATKTool` base class, which is aware of all primary tool inputs and so is able to perform this check automatically -- see `GATKTool.validateSequenceDictionaries()`). At present, we need to do this validation manually in dataflow tools, but it would be nice if we could get it to happen automatically in a base class as it does on the walker side of things.

**Comment by akiezun** [comment]
is spark affected by this?

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/hellbender/pull/955
