### ISSUE TITLE
Make reference mandatory when there is at least one CRAM file in the inputs

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#673]

**Comment by droazen** [comment]
Should be done at the level of `GATKTool`

**Comment by lbergelson** [comment]
you're poking awkward holes in the argument parser here.  Should we try to be able to express this sort of constraint in the argument parser itself?

**Comment by akiezun** [comment]
my vote is no. just check this condition in the gatktool initialization and blow up

**Comment by droazen** [comment]
Yeah, the argument parser should not (and probably cannot) be involved with this kind of check, since the argument for CRAM input is the same as the argument for BAM/SAM input. We'll just add another on startup check in `GATKTool`

**Comment by droazen** [comment]
To clarify this ticket: in `GATKTool.initializeReads()`, just check `readArguments.getReadFiles()` for files ending with a cram extension (should see if there's a canonical method in htsjdk for checking whether a file is cram) -- if you find any and we don't have a reference according to `hasReference()`, throw a `UserException` with a clear error message.

**Comment by droazen** [comment]
Checking whether the **correct** reference has been provided for the cram inputs is a separate task -- once the htsjdk patch in https://github.com/broadinstitute/hellbender/issues/677 propagates to hellbender, we should see whether htsjdk handles that check for us transparently.

**Comment by droazen** [comment]
This one is done.
