### ISSUE TITLE
Stop htsjdk CRAM reader from trying to download the reference when the expected reference is not available.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#677]
Find out if there's a way to disable this awful behavior via `SamReaderFactory` -- if not, let's patch htsjdk itself to turn off reference auto-downloading by default.

**Comment by droazen** [comment]
We should also make sure that hellbender handles the case of "wrong reference for CRAM" gracefully and does not do anything stupid -- what we want is a `UserException` to be thrown with a descriptive error message. We should add an integration test to verify that we handle this properly.

**Comment by droazen** [comment]
htsjdk has been patched (https://github.com/samtools/htsjdk/pull/286) -- before this ticket can be closed, however, we need to wait for the next htsjdk release, rev the htsjdk dependency in hellbender, and ensure that hellbender can now handle the "wrong/missing reference for CRAM" case gracefully with a sensible error message.

**Comment by droazen** [comment]
Re-opening, since we don't yet have a test proving that we handle the "wrong/missing reference for CRAM" cases gracefully (eg., no `NullPointerException` or anything like that! :)

**Comment by droazen** [comment]
Completing https://github.com/broadinstitute/hellbender/issues/673 will take care of the case of "missing reference for CRAM", but we also need to make sure we're handling the case of "wrong reference" elegantly (where elegantly means "throw a `UserException` with a descriptive error message). We want a test case with a reference that is the wrong reference for a CRAM, but has a compatible sequence dictionary (so that it won't be caught by the sequence dictionary validation).

Both the wrong and missing reference cases should have a simple integration test that runs, eg., `PrintReads` with `expectedExceptions = UserException.class`

**Comment by edwardkw** [comment]
Once this is fixed, I will need to un-disable the test for PrintReads that involves CRAM and intervals. #675

**Comment by droazen** [comment]
Closing this, as the core task is done -- fixing the "wrong reference" case is covered by https://github.com/broadinstitute/hellbender/issues/793, and adding a `PrintReads` test involving cram and intervals is covered by https://github.com/broadinstitute/hellbender/issues/675
