### ISSUE TITLE
Determine how to deal with immutability requirement / sibling fusion in dataflow

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#702]
Options include:

-Do nothing, and enforce via coding conventions (and hope the dataflow team comes to its senses).

-Making a copy of the input before every `apply()` / `processElement()` / etc. (only affects dataflow code, but is inefficient (since it copies even when there's no mutation) and brittle since it only affects tools that go through our interface).

-Make our types immutable, and add builders for mutation that perform copies (affects/penalizes non-dataflow code as well, since it will no longer be possible to modify in place).

-Have both mutable and immutable views of each type, plus a builder (hard to manage given dataflow's poor support for polymorphism)

**Comment by droazen** [comment]
We're leaning towards the wrapper option at this point, so as not to penalize non-dataflow code for dataflow's shortcomings.

**Comment by droazen** [comment]
`SafeDoFn` seems to be the winner -- let's implement it

**Comment by droazen** [comment]
Want a `Copyable` interface, plus a `DoFn` wrapper that copies each element and wraps in a new `ProcessContext`

**Comment by droazen** [comment]
As determined by @davidadamsphd , the `Copyable` interface idea won't work:

The recommendation from the Dataflow team was to make a narrow API and do the copying part of the API. I started down this route, and I think it might be doable for things like the walker interface. The idea is to make a Copyable interface and have our interfaces extend that. 

However, we have unsafe code already in the engine. I tried to make this SafeDoFn approach, however it became clear quickly that we'd have a combinatorial explosion of classes because we don't just have DoFn<GATKRead,POut>, but also <Iterable<GATKRead>,POut>, and many others. So, this approach will not work for the engine.

I then tried to make a general purpose solution (using coders to write to bytes and then recreate a new class). This doesn't work for a few reasons, most critical is that the coder registry isn't Serializable, so that can't be passed down deep enough to get this to work.

While working on this, I chatted with someone on the Dataflow team who is working on the verification on the direct runner. He has a PR out and likely going to get it approved soon. So, for the engine, we could always test using the direct runner and know for sure there are not issues (once we can use his code). However, there are two downsides:

1) We will need to wait for a cut of the SDK (which looking at their previous clip is likely ~ two weeks away). 

2) I don't know if we want the direct runner test as our general purpose solution. Can we expect Comp Bios to always test with the direct runner first? Will they write anything more complex than functions that use the Walker interface?

**Comment by droazen** [comment]
Next step is to evaluate using Kryo for the deep copying in the SafeDoFn approach (uses reflection to deep copy all fields via direct assignment (no byte array intermediary)).

**Comment by droazen** [comment]
After an evaluation by @davidadamsphd, we've eliminated Kryo as an option due to its requirement that types either have a default constructor or implement Serializable (a problem for types we don't control).

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#20
