### ISSUE TITLE
delete MarkDuplicatesWithMateCigar and related classes

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/hellbender#729]
@nh13 @yfarjoun I understand this code is not ready / used in production. Is that right?

**Comment by nh13** [comment]
It is ready, but not wired in and used in production.  The reason being that it cannot be used on experiments that have large skips in the alignments (Ns in the Cigars).  Examples include RNA-seq and assembly.

**Comment by akiezun** [comment]
this is done

**Comment by yfarjoun** [comment]
FYI, there are going to be at least 2 tools that are based on this
infrastructure...in Picard-private. Thus, before picard-private can be
build against hellbender, this iterator will be needed.

**Comment by akiezun** [comment]
we'll bring it back it needed. if you could  annotate the requirements docs with this info, it would be great.
