### ISSUE TITLE
upgrade to google-cloud-dataflow-java-sdk-all:0.4.150710

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/hellbender#754]
This isn't just a matter of changing the number. [RegisterCoder was made more stringent] (https://cloud.google.com/dataflow/release-notes/java) and this will force some code changes. Hopefully only little ones, but I got only as far as getting an internal Java error and I think that's a sign I should go to bed.

**Comment by tomwhite** [comment]
I just released Spark Dataflow 0.3.0 which supports Dataflow 0.4.150710, so you should bump the version of that at the same time.

Hopefully that should be sufficient from the Spark side. If not, I'm going on vacation for a week, so I won't be able to help out until I get back I'm afraid :)

**Comment by lbergelson** [comment]
@tomwhite Thanks for the info.  I'll make sure to update spark along with dataflow.  Have a good vacation.

**Comment by lbergelson** [comment]
@jean-philippe-martin David and I solved the compile errors, now we just have several dozen runtime errors...  

Most of them are due to a new requirement that almost every usage of every transform be explicitly given a unique name.  I opened an issue with dataflow to find out more information about what it means to be "stable and unique"  https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/51.  If we actually have to have stable and unique names then we're going to have to add a bunch of boilerplate to thread names through all of our code.  

We're also hitting what may be a dataflow bug where encoding/decoding is consuming all available ram until the jvm crashes.

**Comment by jean-philippe-martin** [comment]
I thought the naming messages were just warnings, not errors?

As for encoding using all the RAM - are you passing it SAMRecords wrapped into GATKReads?

**Comment by lbergelson** [comment]
They've upgraded them from warnings to errors.

**Comment by lbergelson** [comment]
```
    @Test
    public void testGetInvalidPCollectionLocal() {
        // ValidationStringency.SILENT should prevent any read error even though the input has what looks like invalid reads.
        Pipeline p = GATKTestPipeline.create();
        ReadsDataflowSource source = new ReadsDataflowSource(hiSeqBam, p);
        SAMFileHeader header = source.getHeader();
        final SAMSequenceDictionary sequenceDictionary = header.getSequenceDictionary();
        DataflowUtils.registerGATKCoders(p);
        PCollection<GATKRead> reads = source.getReadPCollection(IntervalUtils.getAllIntervalsForReference(sequenceDictionary), ValidationStringency.SILENT);
        PCollection<Long> count = reads.apply(Count.globally());
        // There are 1677 total reads in this file
        DataflowAssert.thatSingleton(count).isEqualTo(1677L);
        p.run();
    }
}
```

Is a failing one with the out of memory errors.  It's invalid in some way SAMRecords being encoded.

**Comment by lbergelson** [comment]
Update:  They added a flag to the TestPipeline that turns the warnings into errors.  We can disable it at some potential future bug cost.

**Comment by jean-philippe-martin** [comment]
If you're encoding SAMRecords, then you may run into the following problem:

`SAMRecord` contain a reference to the header. That reference currently is *not* transient.

The coder for `SAMRecordToGATKReadAdapter` delegates to Java serialization. This will put a copy of the header with each record. Thus we very quickly fill up all the memory.

**Comment by droazen** [comment]
1677 `SAMFileHeader` objects should not fill up all available memory...

**Comment by jean-philippe-martin** [comment]
Perhaps in this case there's some other problem as well.

**Comment by droazen** [comment]
Are self-references a problem for `SerializableCoder`?

**Comment by jean-philippe-martin** [comment]
I wouldn't expect them to be a problem, no.

**Comment by jean-philippe-martin** [comment]
Further experimentation shows that 1677 serialized SAMRecords occupy:
- 76 MB for 1677 headers
- 2 MB for the rest of the records.

That indeed shouldn't fill up RAM, though it's certainly a lot more memory than one may expect. They key issue, aside from the header not being shared, seems to be that the header points to many strings - and they are all de-interned when serialized.
