### ISSUE TITLE
Read CRAM spec to answer important questions

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#755]
We should read the CRAM spec (http://samtools.github.io/hts-specs/CRAMv3.pdf) to find out:

1. Whether CRAM files **always** require a reference, or only sometimes based on the compression used (needed for https://github.com/broadinstitute/hellbender/issues/673)

2. When CRAM compression is lossy vs. lossless (we need to understand this so that when we write the tests for https://github.com/broadinstitute/hellbender/issues/590, we can convert our existing BAMs to CRAM without losing any information).

**Comment by droazen** [comment]
Should report your findings in the thread for this ticket :)

**Comment by droazen** [comment]
Latest CRAM spec is http://samtools.github.io/hts-specs/CRAMv3.pdf. Might also be worth checking out the older 2.1 spec (http://samtools.github.io/hts-specs/CRAMv2.1.pdf) to see if there are any major differences we should care about.

**Comment by edwardkw** [comment]
1. There aren't differences between the two specs, with regards to references. Generally, it seems that reference sequences are often used but not always required. As best I can tell, reference isn't needed for unsorted or unmapped reads. I can't tell about different kinds of compression.

2. There are both kinds of CRAM compression; a wide range of lossy and lossless compression methods exist for CRAM.
