### ISSUE TITLE
Choose approach to fix scaling of ReadBAMTransform, and implement fix

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#756]
From an analysis by @jean-philippe-martin:

**The Problem**

Doing a preliminary performance analysis of Hellbender, I found that ReadBAM did not scale with the number of workers.

![image](https://cloud.githubusercontent.com/assets/798637/8913030/757d9552-3464-11e5-8244-46931fed8383.png)

Logs indicated it was running on a single worker, regardless of how many were specified for the job.

**The Cause**

The underlying cause is a combination of ReadBAM's design and Dataflow's own perhaps over-eager optimization.

ReadBAM is implemented as a series of transforms. It could also have been implemented as a Dataflow BoundedSource, but the latter is much more complicated.

The transforms are as follows:
Start with a collection of filenames and a collection of contigs.
Transform 1 -- input: filenames, side input: contigs. Generates a list of regions to read ("BAMShard")
Transform 2 -- input: `PCollection<BAMShard>`, output: `PCollection<Read>`. Each worker reads from the BAM file, using the index to find where to read from.

Dataflow sees that transform 2 takes as input transform 1's output, and so these two can be run in sequence on the same machines, skipping a serialization/deserialization step. This optimization is called "fusing" and it's generally a very good thing.

However in this case, the input PCollection has a single element (the file we want to read), so only one worker is involved. Because of the fusion, that same worker then ends up doing all of the reading work, ruining our day.

**The Solutions**

There are multiple ways to solve this problem. 

1. change transform 1 to have the contig collection as a primary input in the hope that we always have more than one contig. 
This solution's very brittle (our benchmark, for example, reads a single chromosome so the contig list has effectively only one element). I did not pursue it.

2. Insert a groupby step between the two transforms.
pro: this gets all the workers involved again
con: the groupby itself takes some time, unnecessarily.

3. Compute the BAMShards at the client and then send those to workers.
pro: this gets all the workers involved again, and they do not have to spend any time on groupby
con: an existing Dataflow bug will cause the program to crash if the shard list is too long. We can work around this, though, by increasing the shard size when we have many.

4. Bite the bullet and implement a BoundedSource.

I implemented solutions 2 and 3. Solution 3 is the fastest. I suspect solution 4 wouldn't be any faster, though it would be more idiomatic for Dataflow. The graph below shows the time in the Dataflow Read phase with the new code when using the groupby method (this includes sharding, groupby, and actually reading the BAM file).

![image](https://cloud.githubusercontent.com/assets/798637/8913044/8db099d0-3464-11e5-8ee3-f2cbebb6ce2b.png)

Next Steps

The next step is to pick either solution 3 or 4 (or 2, I suppose, if we want to be expedient). If 3, then we need to change the sharding to deal with large files. If 4, then we need to spend the time and effort writing the new source (and of course testing that it scales as we're expecting).

Comments & feedback welcome!

**Comment by droazen** [comment]
Part of https://github.com/broadinstitute/hellbender/issues/696

**Comment by droazen** [comment]
Not sure what the status of this is -- created this ticket to discuss (it may already be done, in which case feel free to close as resolved!)

**Comment by jean-philippe-martin** [comment]
I think the consensus is: we'll need a liquid sharding BAM reader. But perhaps we'll need a liquid sharding VCF source first, and I'll build that one.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#18
