### ISSUE TITLE
Implement temporary way to write large BAM output in dataflow

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#771]
Until https://github.com/broadinstitute/hellbender/issues/621 is implemented, we need a quick hack for this in order to effectively test the `ReadsPreprocessingPipeline`:

-Need a way of converting GATKRead -> SAM record line (https://github.com/broadinstitute/hellbender/issues/618)

-Add option to ReadsPreprocessingPipeline to bypass `SmallBamWriter` and instead apply a `PCollection<GATKRead>` -> `PCollection<String>` transform, do a `TextIO.Write().to(output).withSuffix()` (might need to disable sharding), then prepend a header, then sort the sam and convert to bam.

**Comment by droazen** [comment]
More details:

Can use hellbender's `SortSAM` to sort the sam output after concatenation, and hellbender's `PrintReads` to convert from sam -> bam

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#21
