### ISSUE TITLE
Fix wrong reference breaking for CRAMs

### ISSUE THREAD

**Issue by edwardkw** [broadinstitute/hellbender#793]

**Comment by droazen** [comment]
(and re-enable test in `CRAMReferenceIntegrationTest` once this is done)

**Comment by droazen** [comment]
Currently we get a `NullPointerException` if the wrong reference is provided for a cram (but the sequence dictionaries are compatible). Ideally we want to query in advance whether a reference matches the one each cram input expects -- if there's no facility to do this, we may need to add a new method to htsjdk.

**Comment by droazen** [comment]
Looks like the problem occurs when the cram dictionary is "compatible" with the reference dictionary according to our validation routines, but the reference dictionary does not contain all contigs from the cram dictionary.

We are going to make our dictionary validation stricter to prevent this (https://github.com/broadinstitute/hellbender/issues/802). We should also patch htsjdk to throw a nicer error than `NullPointerException` in this case -- ie., insert a check after `CRAMIterator` line 158 that throws a `RuntimeException` with a nice "contig from cram header not found in reference" error message if refs == null.
