### ISSUE TITLE
KeyVariantsByRead.key removes reads that don't have variants

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/hellbender#795]
This is a bug in the our Dataflow code. It would be an easy fix if we could just emit a KV where the key was the read without any variants and the value was null. However, Dataflow doesn't allow emitting nulls...

Unfortunately, the real fix will require UUIDs and joining two PCollections :(

**Comment by droazen** [comment]
Doesn't dataflow have left outer join? :)  This is a serious issue, though, as many reads will not have any overlapping known sites from the variants source.

**Comment by davidadamsphd** [comment]
I think the way we create the ReadContextData masks this bug. It only matters for the direct use of the joined reads and variants.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#16
