### ISSUE TITLE
testBQSRCloud is non-deterministic

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#833]
It fails sometimes with the following output:  
[bqsrCloudFailure.txt | uploaded via ZenHub](https://files.zenhub.io/55d38d25a33f044705b9e5a8)

**Comment by jean-philippe-martin** [comment]
You mean [BaseRecalibratorDataflowIntegrationTest.testBQSRCloud](https://github.com/broadinstitute/hellbender/blob/jp_bqsr_skel_rerebased/src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorDataflowIntegrationTest.java#L175)? The one I haven't yet checked in?

**Comment by lbergelson** [comment]
It's in the mandatory cloud group right now.  Is it not expected to work?

**Comment by jean-philippe-martin** [comment]
No, it's not expected to work.

**Comment by lbergelson** [comment]
Ok.  I was confused because we'd put it in the cloud group instead of the cloud_todo so I thought it was supposed to be stablish.  It failed and caused a bunch of confusion since it was a failure of the master branch with all the beer penalties that entails.

**Comment by jean-philippe-martin** [comment]
Ah, I see you didn't mean the one I linked to, but a different one, in master. Yes, it's supposed to work. No, I wouldn't spend effort trying to debug it, since it's about to be replaced by the one I linked to.

**Comment by lbergelson** [comment]
Heh, yes, I'm not usually in the habit of preemptively filing bugs against other people's in progress code.

**Comment by jean-philippe-martin** [comment]
I know, I shouldn't have assumed that your non-denial answer meant "yes", especially since that scenario was unlikely. It's just that I'm fighting with that right now.

**Comment by lbergelson** [comment]
I was just confused by what you were saying.  Confusion all around!  Mass panic!
