### ISSUE TITLE
Expand ReadsSparkSink to write to a sharded-bam

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/hellbender#854]
Currently, it only writes to a single-file BAM.

**Comment by akiezun** [comment]
is this done?

**Comment by davidadamsphd** [comment]
ReadsSparkSink.writeReadsSharded does it right now. The only thing missing
is renaming all of the part files as .bam. I don't know how much we care to
do that.

**Comment by akiezun** [comment]
we don't care as long as the reading code can recognize them and read them. Does it?

**Comment by davidadamsphd** [comment]
I haven't chained these together, but I can use samtools view with no problem. So I assume our tools would work too. (I think we can close this).
