### ISSUE TITLE
strip thread safety from CachingIndexedFastaSequenceFile and move it to htsjdk

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#89]
We can simplify it by removing thread safety guarantees and then push it down into htsjdk

**Comment by akiezun** [comment]
@lbergelson i think thread-safety code is gone. Is it worth the trouble pushing this code down to htsjdk?

**Comment by lbergelson** [comment]
Very low priority, although it would be useful for people using htsjdk directly I think.  It would save us 15s on our test suite to push those tests down too.

@nh13 Would you like this in htsjdk?

**Comment by akiezun** [comment]
i'm going to close this. If people want it in htsjdk, they will enter a ticket.
